language: java
jdk:
  - oraclejdk8
notifications:
  slack: snvx:UluUXbvMSf3GiZvRpWDH2X02
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aac4d704bf2fde965770
  email: false
after_success:
    - mvn clean test jacoco:report coveralls:report
